# Customer UI Service
apiVersion: v1
kind: Service
metadata:
  name: customer-ui
  namespace: purchase-system
  labels:
    app: customer-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: customer-ui
