# Customer Web Server Service
# Internal service accessed via Ingress
apiVersion: v1
kind: Service
metadata:
  name: customer-web-server
  namespace: purchase-system
  labels:
    app: customer-web-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: customer-web-server
